KP-800 [Maven] Map /root/.m2 on agent into docker container to speed build process
Kaholo/kaholo-plugin-maven pull request #4
Opened 2022-06-21 09:00 UTC by xkcm

[**KP-800 in Jira**](https://kaholo.atlassian.net/browse/KP-800)

2022-06-22 10:46 UTC, kenskyfish approved these changes, later dismissed
Works quite nicely!

2022-06-27 06:27 UTC, graddaniel requested changes

2022-06-27 06:27 UTC, graddaniel commented on mvn-cli.js
> +    const volumeDefinition = docker.createVolumeDefinition(workingDirectory);
this is clearly `workingDirectoryVolumeDefinition`

2022-06-27 06:27 UTC, graddaniel commented on mvn-cli.js
> +    dockerEnvironmentalVariables = {
New parameter can be assigned directly to an existing object. No need to recreate it just to achieve that.

2022-06-27 10:13 UTC, graddaniel approved these changes

2022-06-27 14:42 UTC, merged